-- ============================================================
-- University Leadership Appointment Management System
-- PostgreSQL Schema (generated by Prisma — reference copy)
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Enums
CREATE TYPE "Role" AS ENUM (
  'STUDENT','SECRETARY','DEPARTMENT_HEAD','DEAN','VICE_PRESIDENT','PRESIDENT','ADMIN'
);
CREATE TYPE "AppointmentStatus" AS ENUM (
  'PENDING','SECRETARY_APPROVED','APPROVED','REJECTED','CANCELLED','COMPLETED','RESCHEDULED'
);
CREATE TYPE "RescheduleStatus" AS ENUM ('PENDING','APPROVED','REJECTED');
CREATE TYPE "NotificationType" AS ENUM (
  'APPOINTMENT_CREATED','APPOINTMENT_APPROVED','APPOINTMENT_REJECTED',
  'APPOINTMENT_CANCELLED','APPOINTMENT_RESCHEDULED','APPOINTMENT_REMINDER','GENERAL'
);

-- Users
CREATE TABLE users (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name     VARCHAR(100) NOT NULL,
  email         VARCHAR(255) UNIQUE NOT NULL,
  password      VARCHAR(255) NOT NULL,
  role          "Role" NOT NULL DEFAULT 'STUDENT',
  phone         VARCHAR(20),
  department    VARCHAR(100),
  fcm_token     TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Appointments
CREATE TABLE appointments (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id         UUID NOT NULL REFERENCES users(id),
  leader_id            UUID NOT NULL REFERENCES users(id),
  secretary_id         UUID REFERENCES users(id),
  title                VARCHAR(200) NOT NULL,
  description          TEXT,
  date                 DATE NOT NULL,
  start_time           VARCHAR(5) NOT NULL,
  end_time             VARCHAR(5) NOT NULL,
  status               "AppointmentStatus" NOT NULL DEFAULT 'PENDING',
  location             VARCHAR(200),
  cancellation_reason  TEXT,
  secretary_note       TEXT,
  leader_note          TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Reschedule Requests
CREATE TABLE reschedule_requests (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id   UUID NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
  requested_by_id  UUID NOT NULL,
  old_date         DATE NOT NULL,
  old_start_time   VARCHAR(5) NOT NULL,
  old_end_time     VARCHAR(5) NOT NULL,
  new_date         DATE NOT NULL,
  new_start_time   VARCHAR(5) NOT NULL,
  new_end_time     VARCHAR(5) NOT NULL,
  reason           TEXT NOT NULL,
  status           "RescheduleStatus" NOT NULL DEFAULT 'PENDING',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Notifications
CREATE TABLE notifications (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title      VARCHAR(255) NOT NULL,
  message    TEXT NOT NULL,
  type       "NotificationType" NOT NULL DEFAULT 'GENERAL',
  is_read    BOOLEAN NOT NULL DEFAULT FALSE,
  data       JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Audit Logs
CREATE TABLE audit_logs (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID NOT NULL REFERENCES users(id),
  action     VARCHAR(100) NOT NULL,
  entity     VARCHAR(100) NOT NULL,
  entity_id  UUID,
  details    JSONB,
  ip_address VARCHAR(45),
  timestamp  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_appointments_leader_date ON appointments(leader_id, date);
CREATE INDEX idx_appointments_requester ON appointments(requester_id);
CREATE INDEX idx_appointments_secretary ON appointments(secretary_id);
CREATE INDEX idx_appointments_status ON appointments(status);
CREATE INDEX idx_notifications_user ON notifications(user_id, is_read);
CREATE INDEX idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_timestamp ON audit_logs(timestamp DESC);
